name: Deploy

on:
  push:
    branches: 
    - 'master'
  pull_request:
    branches: 
    - 'master'

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
    
        - name: Login to Docker registry
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USER }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}  # Store in a dedicated secret
        
    
        - name: Build And Push
          uses: docker/build-push-action@v5
          with:
            push: true
            context: .
            file: ./Dockerfile
            build-args: |
              PRODUCTION=${{ secrets.PRODUCTION }}
              AUTH_BE=${{ secrets.AUTH_BE }}
              TRANSACTION_BE=${{ secrets.TRANSACTION_BE }}
              COURSE_BE=${{ secrets.COURSE_BE }}
              FORUM_BE=${{ secrets.FORUM_BE }}
            tags: voizcack/orchestrator:latest # ganti voizcrack dgn username dockerhub mu

    deploy:
        runs-on: ubuntu-latest
        needs: publish  # Wait for publish job to complete
        steps:
          - uses: actions/checkout@v4
            
          - name: executing remote ssh commands using password
            uses: appleboy/ssh-action@v1.0.3
            with:
              host: ${{ secrets.GCP_STATIC_IP }}
              username: ${{ secrets.GCP_USERNAME }}
              key: ${{ secrets.SSH_KEY }}
              script: |
                docker container rm -f ${{ secrets.CONTAINER_NAME }} || true
                docker image rm -f ${{ secrets.DOCKERHUB_USER }}/${{ secrets.IMAGE_NAME }}:latest || true
                docker run --name ${{ secrets.CONTAINER_NAME }} -d -p 8811:8800 ${{ secrets.DOCKERHUB_USER }}/${{ secrets.IMAGE_NAME }}:latest